Greedy CC
Janix4000/votepy pull request #10
Opened 2022-04-28 21:39 UTC by msluszniak

2022-04-29 11:57 UTC, msluszniak commented
![](https://github.trello.services/images/mini-trello-icon.png) [Writing a base class/function for calculating greedy algorithms](https://trello.com/c/gwheO6s5/51-writing-a-base-class-function-for-calculating-greedy-algorithms)

2022-04-29 11:58 UTC, msluszniak commented
![](https://github.trello.services/images/mini-trello-icon.png) [CC-rule implementation: Greedy algorithm](https://trello.com/c/pOZ070uq/36-cc-rule-implementation-greedy-algorithm)

2022-05-02 09:29 UTC, Wolokin requested changes
Almost fine

2022-05-02 09:29 UTC, Wolokin commented on votepy/chamberlin-courant.py
> +        committee = set(committee + [candidate])
committee is an Iterable and for most Iterables adding a list won't work. 
```suggestion
        committee = set(committee) + {candidate}
```

2022-05-02 12:10 UTC, merged