Prepare testing environment
Janix4000/votepy pull request #17
Opened 2022-08-31 15:57 UTC by Janix4000

Include `Pytest` and create a directory` tests' with basic helper functions. In the future, we will generate `json` files with test elections and use them to ensure the correctness of our algorithms.

2022-08-31 15:59 UTC, Janix4000 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Find a nice unit test library for python](https://trello.com/c/6EAxwOX9/16-find-a-nice-unit-test-library-for-python)

2022-10-05 12:37 UTC, Wolokin requested changes

2022-10-05 12:37 UTC, Wolokin commented on tests/test_bloc.py
> +    print(os.getcwd())
Should this be here?

2022-10-05 12:37 UTC, Wolokin commented on tests/test_bloc.py
> +        assert (score >= alpha * expected_score)
Why not use assert_approximation here?

2022-10-05 12:37 UTC, Wolokin commented on tests/util/util.py
> +    score = scoring_function(committee)
I believe scoring_function should accept 'voting' as well

2022-10-05 12:37 UTC, Wolokin commented on votepy/k-borda.py
> +from votepy.ordinal_election import OrdinalElection, OrdinalBallot
We should rename this file with an underscore as well

2022-10-09 15:17 UTC, msluszniak commented on tests/util/util.py
> +        test = {}
```suggestion
        test = {"election": election, "scores": []}
```

2022-10-09 15:17 UTC, msluszniak commented on votepy/bloc.py
> +        `ValueError`: Size of committee is a positive number which do not exceeds number of all candidates
```suggestion
        `ValueError`: The size of the committee is a positive integer which does not exceed the number of all candidates
```

2022-10-09 15:17 UTC, msluszniak commented on votepy/bloc.py
> +        `ValueError`: Number of candidates scored in Bloc is a positive number which do not exceeds number of all candidates
```suggestion
        `ValueError`: The number of candidates scored in Bloc is a positive integer which does not exceed the number of all candidates
```

2022-10-11 11:41 UTC, Janix4000 commented on tests/test_bloc.py
> +    print(os.getcwd())
No

2022-10-11 11:45 UTC, Janix4000 commented on tests/test_bloc.py
> +        assert (score >= alpha * expected_score)
To be honest, `assert_approximation` is unnecessary and should be removed.
In many cases it is easier to create this assert by hand.

2022-10-11 11:45 UTC, Janix4000 commented on tests/util/util.py
> +    score = scoring_function(committee)
I removed this function.

2022-10-11 12:10 UTC, msluszniak approved these changes

2022-10-11 12:47 UTC, Wolokin approved these changes

2022-10-11 12:51 UTC, merged