SNTV rule
Janix4000/votepy pull request #7
Opened 2022-04-27 21:30 UTC by Janix4000

2022-04-27 21:30 UTC, Janix4000 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement SNTV rule](https://trello.com/c/1lWmgIcp/6-implement-sntv-rule)

2022-04-28 12:02 UTC, Wolokin requested changes
Small tweak needed

2022-04-28 12:02 UTC, Wolokin commented on votepy/sntv.py
> +        OrdinalBallot: List of chosen candidates wrapped in ordinalBallot
It returns a list, not an OrdinalBallot

2022-04-28 12:15 UTC, Janix4000 commented on votepy/sntv.py
> +        OrdinalBallot: List of chosen candidates wrapped in ordinalBallot
Fixed

2022-04-28 12:20 UTC, Wolokin approved these changes
Ok

2022-04-28 18:25 UTC, merged